@baseUrl = {{baseUrl}}

### Get all contacts
GET http://localhost:3000/students/68cf25a08222d64a3dfa1219 HTTP/1.1
Content-Type: application/json

### GET {{baseUrl}}/contacts HTTP/1.1
GET https://enrolment-manager.onrender.com/students HTTP/1.1
Content-Type: application/json

### Get a single contact by ID https://enrolment-manager.onrender.com
GET GET https://enrolment-manager.onrender.com/students HTTP/1.1
Content-Type: application/json

### Create contact
POST https://enrolment-manager.onrender.com/students/post HTTP/1.1
Content-Type: application/json

{
    "first_name": "Odudua1",
    "last_name": "Yoruba1",
    "email": "odeh.abah@example.com",
    "phone_number": "+2348098765432",
    "course": "Mechanical Engineering",
    "enrollment_date": "2023-11-20",
    "status": "Graduated",
    "gpa": 3.60
}

### Update a contact
PUT https://enrolment-manager.onrender.com/students HTTP/1.1
Content-Type: application/json

{
    "first_name": "Odu",
    "last_name": "Yoru",
    "email": "abrahimttt.mukaila@example.com",
    "phone_number": "+234809870987",
    "course": "Medic",
    "enrollment_date": "2020-11-20",
    "status": "Graduated",
    "gpa": 4.00

}
### Update a contact
GET  http://localhost:3000 HTTP/1.1
Content-Type: application/json

### Delete a contact
DELETE  https://enrolment-manager.onrender.com/students/delete/68cfe807b4a8ea00ebb48aa4 HTTP/1.1

### GET {{baseUrl}}/contacts/68bd7ee59498bdf2085f68cd HTTP/1.1